# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main_launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('icon.ico', '.'),
        ('config.py', '.'),
        ('dna_analyzer_gui.py', '.'),
        ('dna_dashboard.py', '.'),
        ('dna_exceptions.py', '.'),
        ('dna_explainability.py', '.'),
        ('dna_feature_engineering.py', '.'),
        ('dna_insights_generator.py', '.'),
        ('dna_logging.py', '.'),
        ('dna_model_inference.py', '.'),
        ('dna_model_registry.py', '.'),
        ('dna_model_trainer.py', '.'),
        ('evaluate_model.py', '.'),
        ('performance_dna_analyzer.py', '.'),
        ('promote_model.py', '.'),
        ('retrain_dna_model.py', '.'),
        ('train_dna_model.py', '.'),
        ('README.md', '.'),
        ('barber', 'barber'),
        ('COTA', 'COTA'),
        ('Road America', 'Road America'),
        ('Sebring', 'Sebring'),
        ('Sonoma', 'Sonoma'),
        ('VIR', 'VIR'),
        ('models', 'models'),
        ('training_artifacts', 'training_artifacts'),
    ],
    hiddenimports=[
        'customtkinter',
        'tkinter',
        'PIL',
        'PIL._tkinter_finder',
        'pandas',
        'numpy',
        'matplotlib',
        'seaborn',
        'plotly',
        'torch',
        'sklearn',
        'scipy',
        'sklearn.ensemble',
        'sklearn.tree',
        'sklearn.utils._cython_blas',
        'sklearn.neighbors.typedefs',
        'sklearn.neighbors.quad_tree',
        'sklearn.tree._utils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MTP DNA Analyzer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='MTP DNA Analyzer',
)
